// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjWDpHN5wjONz5Z-4Pddis3k_HBb9QLkU',
    appId: '1:348753748050:web:12aca706e18b9988b57f8b',
    messagingSenderId: '348753748050',
    projectId: 'hubbles-48a01',
    authDomain: 'hubbles-48a01.firebaseapp.com',
    storageBucket: 'hubbles-48a01.appspot.com',
    measurementId: 'G-Y7ZMM8V00M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMn9c8ryrVhAMEm6vPLDmxbgRW4wdxirI',
    appId: '1:348753748050:android:3f9266792420a7a8b57f8b',
    messagingSenderId: '348753748050',
    projectId: 'hubbles-48a01',
    storageBucket: 'hubbles-48a01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLH_A5Ua9AW_L1qPJf_yje2mDYot-kN1o',
    appId: '1:348753748050:ios:afd1b6afd7b24eafb57f8b',
    messagingSenderId: '348753748050',
    projectId: 'hubbles-48a01',
    storageBucket: 'hubbles-48a01.appspot.com',
    iosBundleId: 'com.example.hubbles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLH_A5Ua9AW_L1qPJf_yje2mDYot-kN1o',
    appId: '1:348753748050:ios:921c9c8d451ddd4eb57f8b',
    messagingSenderId: '348753748050',
    projectId: 'hubbles-48a01',
    storageBucket: 'hubbles-48a01.appspot.com',
    iosBundleId: 'com.example.hubbles.RunnerTests',
  );
}
